uecryptfs: fixed typo

diff --git a/sbin/uecryptfs b/sbin/uecryptfs
--- a/sbin/uecryptfs
+++ b/sbin/uecryptfs
@@ -10,9 +10,9 @@ USER=$1
 USERHOME=$(awk -F: "/^$USER:/{print\$6}" /etc/passwd)
 modprobe ecryptfs || abort "Could not modprobe ecryptfs"
 [ -d $USERHOME ] || abort "Could not find home directory"
-[ -f $USERHOME/.ecryptffssettings ] || abort "Could not find ecryptfs settings"
+[ -f $USERHOME/.ecryptfssettings ] || abort "Could not find ecryptfs settings"
 [ -d $USERHOME/.encrypted ] || abort "Could not find encrypted directory"
 [ -d $USERHOME/.decrypted ] || abort "Could not find decrypted directory"
 echo "Mounting with:"
-echo mount -t ecryptfs -o $(cat $USERHOME/.ecryptffssettings) $USERHOME/.encrypted $USERHOME/.decrypted
-mount -t ecryptfs -o $(cat $USERHOME/.ecryptffssettings) $USERHOME/.encrypted $USERHOME/.decrypted
+echo mount -t ecryptfs -o $(cat $USERHOME/.ecryptfssettings) $USERHOME/.encrypted $USERHOME/.decrypted
+mount -t ecryptfs -o $(cat $USERHOME/.ecryptfssettings) $USERHOME/.encrypted $USERHOME/.decrypted
